### ISSUE TITLE
Keine Informationen zur Anmeldung vorhanden

### ISSUE THREAD

**Issue by polybos** [netz39/sommercamp2014#2]
Auf der Webseite ist nicht hinterlegt, dass man sich per Mail an sommercamp@netz39.de anmelden muss.
Für Leute, die die Ankündigungsmail nicht mehr haben evtl. eine sehr große Hürde.

**Comment by apfohl** [comment]
Naja, das ist absicht, da sich ja nicht jeder der auf die Seite stößt anmelden können soll.

**Comment by penguineer** [comment]
Wobei das Camp ja auch nicht gerade überlaufen ist und man durchaus über eine Öffnung nachdenken könnte. Der Link steht ja jetzt auch nicht an jeder Ecke des internets.
