### ISSUE TITLE
Seite nicht sichtbar

### ISSUE THREAD

**Issue by penguineer** [netz39/sommercamp2014#3]
Wenn ich die URL aufrufe, wird im Browser nichts angezeigt.

Optionen:
* die Seite wird gefixt
* wir schalten die Seite ab (ggf. Informationen ins Wiki übertragen)

**Comment by LeSpocky** [comment]
Laut [Plenumsbeschluss](http://www.netz39.de/wiki/stammtisch:2018:2018-02-07) wird die Seite (DNS) abgeschaltet und das Repo hier archiviert. Werde ich mich drum kümmern.
